CREATE TABLE hardware (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          naziv VARCHAR(100) NOT NULL,
                          cijena INTEGER NOT NULL,
                          tip VARCHAR(50) NOT NULL,
                          sifra INTEGER,
                          kolicina INTEGER NOT NULL
);