/*CREATE TABLE hardware (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          naziv VARCHAR(100) NOT NULL,
                          cijena INTEGER NOT NULL,
                          tip VARCHAR(50) NOT NULL,
                          sifra INTEGER,
                          kolicina INTEGER NOT NULL
);*/

IF OBJECT_ID('dbo.[Type]', 'U') IS NULL
CREATE TABLE dbo.[Type] (
                            id INT IDENTITY(1,1) PRIMARY KEY,
    naziv VARCHAR(50) NOT NULL UNIQUE
    );

IF OBJECT_ID('dbo.Hardware', 'U') IS NULL
CREATE TABLE dbo.Hardware (
                              id BIGINT IDENTITY(1,1) PRIMARY KEY,
                              naziv VARCHAR(100) NOT NULL,
                              cijena INT NOT NULL,
                              tip_id INT NOT NULL,
                              sifra INT,
                              kolicina INT NOT NULL,
                              CONSTRAINT FK_Hardware_Type
                                  FOREIGN KEY (tip_id)
                                      REFERENCES dbo.[Type](id)
);